<?php
/*
-----------------
Lenguaje: Español
-----------------
*/
  $lengua= [
    "SITE_NAME" => "FastPacket - Mensajer&iacute;a Freelance",
    "TITULO_WEB" => "FastPacket",
	"SALUDO" => "Bienvenido",
	"SLOGAN" => "Conectamos a cualquiera que necesite hacer un envio con el mensajero",
	"HEADING" => "FastPacket",
	"HEADING2" => "Encuentra mensajeros",
	"HEADING3" => "Introduzca su c&oacute;digo postal",
	"BUSCAR" => "BUSCAR",
	"BUSCAMENSAJEROS" => "Mensajeros en tu zona",
	"TEXTOPRESENTACION" => "Mensajer&iacute;a Freelance",
	"TEXTOPRESENTACION2" => "Gestiona tus propios envios",
	"MENU_LENGUAJES" => "Lenguajes",
	"MENU_TEXTO" => "Men&uacute;",
	"MENU_ESPANOL" => "Espa&ntilde;ol",
	"MENU_INGLES" => "Ingl&eacute;s",
	"MENU_LOGIN" => "Entrar",
	"MENU_INICIO" => "Inicio",
	"MENU_REGISTRO" => "Registrarse",
	"MENU_EDITAR" => "Mi perfil",
	"MENU_SALIR" => "Salir",
	"SERCLIENTE" => "Ser cliente",
	"MENU_CONOCER" => "Conoce un poco m&aacute;s",
	"SERMENSA" => "Ser mensajero",
	"LOGIN_TITLE" => "Introduzca usuario y contrase&ntilde;a",
	"LOGIN_NUEVO" => "Nuevo Usuario",
	"LOGIN_RECUPERAR" => "¿Olvid&oacute; su contrase&ntilde;a?",
	"LOGIN_VOLVER" => "Ir al inicio",
	"LOGIN_REENVIAR" => "Enviar nueva",
	"LOGIN_ENTRAR" => "Entrar",
	"LOGIN_USUARIO" => "Usuario",
	"LOGIN_CLAVE" => "Contrase&ntilde;a",
	"ERROR_LOGIN" => "El intento de conexi&oacute;n no fue correcto. Int&eacute;ntelo de nuevo",
	"RECUPERAR_CORRECTO" => "Clave enviada correctamente",
	"RECUPERAR_ERROR" => "No se ha podido recuperar el usuario",
	"RECUPERAR_TITLE" => "Recuperar contrase&ntilde;a",
    "ACTIVAR_TITLE" => "Activar cuenta",
	"REGISTRO_CORRECTO" => "Usuario registrado correctamente",
	"REGISTRO_ERROR" => "Ya existe este Usuario",
    "REGISTRO_OK_TITLE"=>"REGISTRO CORRECTO",
    "REGISTRO_OK_AVISO1"=>"Gracias por registrarse en nuestro sitio. <br />Su cuenta ha sido creada, y debe ser activada antes de poder ser utilizada",
    "REGISTRO_OK_AVISO2"=>"Revise la cuenta de correo proporcionada en el registro y active cuanto antes su cuenta para poder utilizar nuestros servicios",
	"REGISTRO_TITLE" => "Rellene el siguiente formulario",
	"REGISTRO_ENTRAR" => "Entrar",
	"REGISTRO_GUARDAR" => "Guardar",
	"REGISTRO_ACTIVACION" => "Enviar autorizaci&oacute;n",
	"AVISOCLAVE" => "Recuerde que FastPacket nunca le pedir&aacute; por correo ninguna informaci&oacute;n personal, ni de sus claves, usuarios y/o envios",
    "ZONA_CLIENTE" =>"ZONA CLIENTE",
    "ZONA_MENSAJERO"=>"PEDIDOS ACEPTADOS",
    "ZONA_PEDIDOS_LIBRES"=>"PEDIDOS LIBRES",
    "TEXTO_PEDIDOS_ACEPTADOS"=>"PEDIDOS ACEPTADOS",
    "TEXTO_PERSONA_ENVIA"=>"PERSONA QUE ENVIA EL PEDIDO",
    "TEXTO_PEDIDOS_LIBRES"=>"PEDIDOS LIBRES",
    "TEXTO_RESUMEN"=>"RESUMEN",
    "BOTON_BUSCAR" =>"Buscar",
    "BOTON_VER_PEDIDO" =>"VER PEDIDO",
    "BOTON_VER_PERFIL" =>"PERFIL",
    "BOTON_RECORRIDO" =>"RECORRIDO",
    "BOTON_ACEPTAR_PEDIDO"=>"ACEPTAR PEDIDO",
    "BOTON_PRESENTAR_OFERTA"=>"PRESENTAR OFERTA",
    "BOTON_PRIMER_ENVIO"=>"REALICE SU PRIMER ENVIO",
    "BOTON_PRIMER_ENVIO_ACEPTADO"=>"ACEPTE SU PRIMER ENVIO",
    "TEXTO_SALIDA" =>"Día recogida",
    "TEXTO_LLEGADA" =>"Día de entrega",
    "TEXTO_DIRECCION_SALIDA" =>"Dirección recogida",
    "TEXTO_DIRECCION_LLEGADA" =>"Dirección entrega",
    "TEXTO_ATT_SALIDA"=>"Att. Recogida",
    "TEXTO_ATT_LLEGADA"=>"Att. Entrega",
    "TEXTO_OBSERVACIONES"=>"Observaciones",
    "TEXTO_ALTO"=>"Alto",
    "TEXTO_ANCHO"=>"Ancho",
    "TEXTO_PROFUNDO"=>"Profundo",
    "TEXTO_DISTANCIA"=>"Distancia",
    "TEXTO_COSTE"=>"Coste",
    "TEXTO_PERFIL"=>"Perfil",
    "TEXTO_NOMBRE"=> 'Nombre',
    "TEXTO_TELEFONO"=> 'Teléfono',
    "TEXTO_EMAIL"=> 'Email',
    "TEXTO_SALIDA_TITLE"=> 'Salida',
    "TEXTO_ENTREGA_TITLE"=>'Entrega',

    "TEXTO_MENSAJERO"=> 'Mensajero',
    "TEXTO_PAQUETE"=>"PAQUETE",
    "TEXTO_OPCIONES"=>"OPCIONES",
    "TEXTO_BULTOS"=>"Nº Bultos",
    "TEXTO_MI_LISTADO"=>"Mis envios",
    "TEXTO_PEDIDO"=>"Pedido Nº",
    "AVISO_SIN_ENVIOS_LIBRES"=>"No hay pedidos que entregar. <br/> En cuanto haya alguno por tu zona te avisaremos al email facilitado.",
    "AVISO_SIN_ENVIOS"=>"Aún no ha realizado ningún envio con nosotros. <br/> Empiece ahora a gestionar sus propios envios.",
    "AVISO_SIN_ENVIOS_ACEPTADOS"=>"Aún no ha aceptado ninguna entrega con nosotros. <br/> Compruebe los pedidos activos y acepte alguno.",
    "AVISO_SIN_ACEPTAR"=>"Ningún mensajero ha aceptado el envio",
    "ACTIVAR_CORRECTO"=>"Gracias por activar su cuenta<br />Su cuenta ha sido activada, ya puede empezar a utilizar la aplicación.",
    "ACTIVAR_ERROR"=>"No se ha podido activar su cuenta. Si el problema persiste contacte con el administrador del sistema.",
    "REENVIO_ERROR" => "Ha ocurrido un error el enviar el email de activaci&oacute;n",
	"REENVIO_CORRECTO" => "Reenvio Correcto. Compruebe la bandeja de entrada y active su cuenta. Si no nos  tiene como envio seguro comprueba la carpeta de spam.",
    "REENVIO_NO"=>"Su cuenta a&uacute;n no ha sido activada<br />Revise su correo y active su cuenta desde el enlace proporcionado.<br/>Si lo desea puede reenviar la autorizaci&oacute;n de nuevo a su email."
];


/* $lang = array();
$lang['SITE_NAME'] = 'FastPacket - Mensajer&iacute;a Freelance';
$lang['TITULO_WEB'] = 'FastPacket';
$lang['SALUDO'] = 'Bienvenido';

$lang['SLOGAN'] = 'Conectamos a cualquiera que necesite hacer un envio con el mensajero';
$lang['HEADING'] = 'FastPacket';
$lang['HEADING2'] = 'Encuentra mensajeros en tu zona';
$lang['HEADING3'] = 'Introduzca su c&oacute;digo postal';
$lang['BUSCAR'] = 'BUSCAR';
$lang['BUSCAMENSAJEROS'] = 'Mensajeros en tu zona';
$lang['TEXTOPRESENTACION'] = 'Mensajer&iacute;a Freelance';
$lang['TEXTOPRESENTACION2'] = 's&eacute; tu propio jefe';
$lang['TEXTOPRESENTACION3'] = 'o gestiona tus propios envios';
$lang['MENU_LENGUAJES'] = 'Lenguajes';
$lang['MENU_TEXTO'] = 'Men&uacute;';
$lang['MENU_ESPANOL'] = 'Espa&ntilde;ol';
$lang['MENU_INGLES'] = 'Ingl&eacute;s';
$lang['MENU_LOGIN'] = 'Entrar';
$lang['MENU_INICIO'] = 'Inicio';
$lang['MENU_REGISTRO'] = 'Registrarse';
$lang['MENU_EDITAR'] = 'Mi perfil';
$lang['MENU_SALIR'] = 'Salir';
$lang['SERCLIENTE'] = 'Ser cliente';
$lang['MENU_CONOCER'] = 'Conoce un poco m&aacute;s';
$lang['SERMENSA'] = 'Ser mensajero';
$lang['LOGIN_TITLE'] = 'Introduzca usuario y contrase&ntilde;a';
$lang['LOGIN_NUEVO'] = 'Nuevo Usuario';
$lang['LOGIN_RECUPERAR'] = '¿Olvid&oacute; su contrase&ntilde;a?';
$lang['LOGIN_VOLVER'] = 'Ir al inicio';
$lang['LOGIN_REENVIAR'] = 'Enviar nueva';
$lang['LOGIN_ENTRAR'] = 'Entrar';
$lang['LOGIN_USUARIO'] = 'Usuario';
$lang['LOGIN_CLAVE'] = 'Contrase&ntilde;a';
$lang['ERROR_LOGIN'] = 'El intento de conexi&oacute;n no fue correcto. Int&eacute;ntelo de nuevo';
$lang['RECUPERAR_CORRECTO'] = 'Clave enviada correctamente';
$lang['RECUPERAR_ERROR'] = 'No se ha podido recuperar el usuario';
$lang['RECUPERAR_TITLE'] = 'Recuperar contrase&ntilde;a';
$lang['REGISTRO_CORRECTO'] = 'Usuario registrado correctamente';
$lang['REGISTRO_ERROR'] = 'Ya existe este Usuario';
$lang['REGISTRO_TITLE'] = 'Rellene el siguiente formulario';
$lang['REGISTRO_ENTRAR'] = 'Entrar';
$lang['REGISTRO_GUARDAR'] = 'Guardar';
$lang['REGISTRO_ACTIVACION'] = 'Enviar autorizaci&oacute;n';
$lang['AVISOCLAVE']='Recuerde que FastPacket nunca le pedir&aacute; por correo ninguna informaci&oacute;n personal, ni de sus claves, usuarios y/o envios';
*/